### ISSUE TITLE
There is something wrong in Configuration , about EnvName.

### ISSUE THREAD

**Issue by zhrli** [abhisheknaik96/continuing-rl-exps#1]
'exp_name': 'puckworld1D_cont_CDiscDDPG', 'env_name': 'puckworld_continuous_1d', 'env_type': 'csuite', 'agent_name': 'CD_DDPG', 'nonlinear': True, 'exp_type': 'control', 'render': False, 'num_runs': 5, 'num_max_steps': 100000, 'eval_every_n_steps': 5000, 'param_update_freq': 32, 'net_sync_freq': 32, 'batch_size': 128, 'buffer_size': 10000, 'actor_arch': [3, 64, 64, 1], 'critic_arch': [4, 64, 64, 1], 'num_actions': 1, 'use_ou_noise': True, 'initial_exploration_only_steps': 10000, 'num_weights': 0, 'actor_optimizer': 'Adam', 'critic_optimizer': 'Adam', 'save_weights': 0, 'store_max_action_values': True, 'robust_to_initialization': True, 'tau': 0.95, 'save_model_loc': 'models/', 'device': 'cpu', 'reward_offset': 0, 'actor_step_size': 0.001, 'critic_step_size': 0.001, 'eta': 0.0, 'gamma': 0.99, 'exp_id': 0, 'output_folder': 'results/test_exp/'}

  0%|          | 0/5 [00:00<?, ?it/s]
  0%|          | 0/5 [00:00<?, ?it/s]

***

Traceback (most recent call last):
  File "/home/lizhaorui/DL/continuing-rl-exps/main.py", line 38, in <module>
    log = run_experiment_one_config(config)
  File "/home/lizhaorui/DL/continuing-rl-exps/experiments.py", line 201, in run_experiment_one_config
    env = csuite.load(env_map[env_name], settings)
  File "/home/lizhaorui/anaconda3/envs/FL/lib/python3.9/site-packages/csuite/__init__.py", line 65, in load
    name = EnvName(name)
  File "/home/lizhaorui/anaconda3/envs/FL/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/home/lizhaorui/anaconda3/envs/FL/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'puckworld_continuous_1d' is not a valid EnvName

And I tried other configurations, not work.

I think your work will help me a lot in improving my RL work in finance. Thank you .

**Comment by abhisheknaik96** [comment]
Hello, you are likely using code from the `dev` branch, which is still under development. Can you try using the `main` branch? I'll update the `dev` code and merge it into `main` soon.
